--
-- PostgreSQL database dump
--

\restrict kc4JOEk6T61eOI3mMUGBR4eKa4fNGzSBzLmH4eq0bMQGqv8NzOdPCR8TayRQRJT

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-11-29 09:59:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4825 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 508193)
-- Name: tb_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_roles (
    role_id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.tb_roles OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 508192)
-- Name: tb_roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 508198)
-- Name: tb_tweets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_tweets (
    tweet_id bigint NOT NULL,
    content character varying(280),
    creation_timestamp timestamp(6) with time zone,
    user_id uuid
);


ALTER TABLE public.tb_tweets OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 507972)
-- Name: tb_tweets_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_tweets_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_tweets_seq OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 508203)
-- Name: tb_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_users (
    user_id uuid NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.tb_users OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 508210)
-- Name: tb_users_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_users_roles (
    user_id uuid NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.tb_users_roles OWNER TO postgres;

--
-- TOC entry 4816 (class 0 OID 508193)
-- Dependencies: 219
-- Data for Name: tb_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_roles (role_id, name) FROM stdin;
1	ADMIN
2	BASIC
\.


--
-- TOC entry 4817 (class 0 OID 508198)
-- Dependencies: 220
-- Data for Name: tb_tweets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_tweets (tweet_id, content, creation_timestamp, user_id) FROM stdin;
2	Criado pelo admin!	2025-11-28 23:03:09.46193-03	1ae276bc-19b9-44b4-b5c7-b02bd1426dc4
102	mais um tweet criado pelo bruno!	2025-11-29 09:12:54.822598-03	fd67062b-2176-4360-b827-075d40bb66ae
\.


--
-- TOC entry 4818 (class 0 OID 508203)
-- Dependencies: 221
-- Data for Name: tb_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_users (user_id, password, username) FROM stdin;
1ae276bc-19b9-44b4-b5c7-b02bd1426dc4	$2a$10$Yil2Q3WPL8dR9S8aFMXRt.nxoLSvS4w.91Wo.litEecGfQNuqA2k2	admin
5f0ad158-a678-4502-beea-b1e9f82ccce4	$2a$10$hEhArY1PlepMw1QAWnfVY.xzcUpwHIAEShj70FQZjZ5iWySCvQuGK	user
fd67062b-2176-4360-b827-075d40bb66ae	$2a$10$BHn5IUD9IsVnapCs/4ai4./YpcyMJIv0HsL2ZUX0lc5cZqe5RPQ9a	bruno
\.


--
-- TOC entry 4819 (class 0 OID 508210)
-- Dependencies: 222
-- Data for Name: tb_users_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_users_roles (user_id, role_id) FROM stdin;
1ae276bc-19b9-44b4-b5c7-b02bd1426dc4	1
5f0ad158-a678-4502-beea-b1e9f82ccce4	2
fd67062b-2176-4360-b827-075d40bb66ae	2
\.


--
-- TOC entry 4826 (class 0 OID 0)
-- Dependencies: 218
-- Name: tb_roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_roles_role_id_seq', 2, true);


--
-- TOC entry 4827 (class 0 OID 0)
-- Dependencies: 217
-- Name: tb_tweets_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_tweets_seq', 151, true);


--
-- TOC entry 4655 (class 2606 OID 508197)
-- Name: tb_roles tb_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_roles
    ADD CONSTRAINT tb_roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4659 (class 2606 OID 508202)
-- Name: tb_tweets tb_tweets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_tweets
    ADD CONSTRAINT tb_tweets_pkey PRIMARY KEY (tweet_id);


--
-- TOC entry 4661 (class 2606 OID 508209)
-- Name: tb_users tb_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4665 (class 2606 OID 508214)
-- Name: tb_users_roles tb_users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_users_roles
    ADD CONSTRAINT tb_users_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 4657 (class 2606 OID 508216)
-- Name: tb_roles uk8ghpmg7galg4xu5qu0feu2cmi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_roles
    ADD CONSTRAINT uk8ghpmg7galg4xu5qu0feu2cmi UNIQUE (name);


--
-- TOC entry 4663 (class 2606 OID 508218)
-- Name: tb_users uk8n82lwp7lflhwda2v2v3wckc9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT uk8n82lwp7lflhwda2v2v3wckc9 UNIQUE (username);


--
-- TOC entry 4667 (class 2606 OID 508229)
-- Name: tb_users_roles fk5xc4yvfrjcy8bl01kq3crp8pg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_users_roles
    ADD CONSTRAINT fk5xc4yvfrjcy8bl01kq3crp8pg FOREIGN KEY (user_id) REFERENCES public.tb_users(user_id);


--
-- TOC entry 4666 (class 2606 OID 508219)
-- Name: tb_tweets fk8igcgf9ddaocdlg9c8scf01vm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_tweets
    ADD CONSTRAINT fk8igcgf9ddaocdlg9c8scf01vm FOREIGN KEY (user_id) REFERENCES public.tb_users(user_id);


--
-- TOC entry 4668 (class 2606 OID 508224)
-- Name: tb_users_roles fkj5qged12p22eloqw5g4f9hm2e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_users_roles
    ADD CONSTRAINT fkj5qged12p22eloqw5g4f9hm2e FOREIGN KEY (role_id) REFERENCES public.tb_roles(role_id);


-- Completed on 2025-11-29 09:59:43

--
-- PostgreSQL database dump complete
--

\unrestrict kc4JOEk6T61eOI3mMUGBR4eKa4fNGzSBzLmH4eq0bMQGqv8NzOdPCR8TayRQRJT

